spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: adlan
    password: adlan
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    databse: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-server: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.maj.ecommerce.notification.PaymentNotificationRequest #untuk informasi ke customer object apa yang dikirim

server:
  port: 8060